[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Doichain"
authors = [{name = "Nico Krause", email = "nico@le-space.de"}]
dynamic = ["version", "description"]
